Model
olangness/WebCrawler pull request #6
Opened 2020-12-07 23:35 UTC by stpenney

2020-12-07 23:46 UTC, olangness requested changes
Make sure your models are separate from the view. The models have no knowledge of the view.

2020-12-07 23:46 UTC, olangness commented on WebCrawler/MainWindow.xaml
> +
These should not be here. The model should work regardless of view/ui components. These need to be arguments to an api or something. Think of his as you making a web crawling library for C#

2020-12-07 23:46 UTC, olangness commented on WebCrawler/MainWindow.xaml.cs
>      public partial class MainWindow : Window
This code should not be in mainwindow class. Models have no knowledge of view. It needs to be separate as a model and not in the codebehind.

2020-12-07 23:46 UTC, olangness commented on WebCrawler/obj/Debug/App.g.cs
> +﻿#pragma checksum "..\..\App.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "68BC721C71289E071597F392E11D572D9C8353B2"
Delete all the files in in the obj/Debug folder. for some reason the .gitignore isnt working and we dont need these build files. I think the issue will be fixed once #5 is merged

2020-12-08 00:44 UTC, olangness requested changes

2020-12-08 00:44 UTC, olangness commented on WebCrawler/Model/LinkParser.cs
> +        #endregion
These can all be [auto implemented properties](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/properties#auto-implemented-properties). Way nicer

2020-12-08 00:44 UTC, olangness commented on WebCrawler/Model/Page.cs
> +}
Use [Auto Implemented Properties ](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/properties#auto-implemented-properties) to make it nicer and easier to change

2020-12-08 00:45 UTC, olangness commented
Also I dont know if you guys are done or not so If you only want me to review your changes once you are done just close this pr and make one once you are actually done and ready to pull request

2020-12-08 22:53 UTC, DrewWick approved these changes

2020-12-08 22:53 UTC, DrewWick submitted a review, later dismissed

2020-12-09 23:47 UTC, olangness approved these changes, later dismissed

2020-12-09 23:54 UTC, olangness approved these changes

2020-12-09 23:54 UTC, merged